# Generated by Django 5.0.3 on 2024-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercerEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
