# Generated by Django 5.0.3 on 2024-03-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercerEntrega', '0002_alter_alumno_contraseña_alter_profesor_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='contraseña',
            new_name='contrasenia',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
