# Generated by Django 5.0.3 on 2024-04-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercerEntrega', '0002_alter_usuario_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='AppTercerEntrega.curso'),
        ),
    ]
