# Generated by Django 5.0.3 on 2024-03-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercerEntrega', '0003_rename_contraseña_alumno_contrasenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='cursos',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=128)),
                ('es_profesor', models.BooleanField(default=False)),
                ('imagen', models.FileField(upload_to='files/imagenes')),
                ('cursos', models.ManyToManyField(to='AppTercerEntrega.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTercerEntrega.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTercerEntrega.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
